---

name: Build docker image (release)

concurrency: "docker-release"

on:
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: nhatthm/gh-actions/checkout@master

      - name: Build and push
        uses: nhatthm/gh-actions/docker-build-and-push@master
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          context: .
          push: true
          file: resources/docker/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            VERSION=${{ github.event.release.tag_name }}
            USER=${{ github.actor }}
            REVISION=${{ github.sha }}

  notify-update-registry:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Notify registries
        uses: nhatthm/gh-actions/notify-go-registries@master
        with:
          token: ${{ secrets.REGISTRY_TOKEN }}
          module: "false"
