---
name: 'update-registry'

on:
  push:
    branches:
      - master
    tags:
      - "**"
  registry_package:
    types: [published]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        registry: [ go.nhat.io, go-staging.nhat.io ]
    steps:
      - uses: actions/checkout@v4

      - id: vars
        run: |
          make gha-vars

      - name: notify ${{ matrix.registry }}
        uses: benc-uk/workflow-dispatch@v121
        with:
          workflow: build
          repo: nhatthm/${{ matrix.registry }}
          token: ${{ secrets.REGISTRY_TOKEN }}
          inputs: '{"modules": "${{ steps.vars.outputs.MODULE_NAME }}"}'
          ref: 'master'
